#!/usr/bin/env php
<?php

if (!$loader = include __DIR__ . '/vendor/autoload.php') {
    die('You must set up the project dependencies.');
}

$app = new \Cilex\Application('Cilex');

// Add your custom commands bellow
$app->command(new \app\command\HelloCommand());

$app->run();
